version: '3.8'

services:
  blink:
    build: .
    container_name: blink_server
    ports:
      - "21337:21337"
    environment:
      - ADMIN_PASSWORD
      - JWT_SECRET
    volumes:
      - blink_data:/app/data
    restart: unless-stopped

volumes:
  blink_data:
